import { createFetch, createSchema } from "@better-fetch/fetch";
import { defineErrorCodes, type BetterAuthPlugin } from "better-auth";
import { APIError, createAuthEndpoint } from "better-auth/api";
import { z } from "zod";

const inputSchema = z.object({
  tenant: z.string(),
  client_id: z.string(),
  scope: z.string(),
  client_secret: z.string(),
  grant_type: z.literal("client_credentials"),
});

const outputSchema = z.object({
  access_token: z.string(),
  expires_in: z.number(),
  token_type: z.string(),
});

const clientCredentialBodySchema = z.object({
  applicationName: z.string(),
});

const defaultErrorSchema = z.object({
  error: z.string(),
  error_description: z.string(),
  error_codes: z.number().array(),
  timestamp: z.coerce.date(),
  trace_id: z.string(),
  correlation_id: z.string(),
});

const msSocialProviderConfigSchema = z.object({
  tenantId: z.string(),
  clientId: z.string(),
  clientSecret: z.string(),
});

export const CLIENT_CREDENTIAL_ERRORS = defineErrorCodes({
  MICROSOFT_PROVIDER_NOT_CONFIGURED:
    "Microsoft social provider is not configured",
  MICROSOFT_PROVIDER_INVALID_CONFIG:
    "Microsoft provider configuration is invalid",
  MICROSOFT_TOKEN_REQUEST_FAILED: "Failed to fetch Microsoft OAuth token",
  MICROSOFT_APPLICATION_NOT_FOUND: "Provided Application not found",
});

/**
 * Configuration for the `clientCredential` plugin.
 *
 * Each key is an **application name** — a caller-chosen identifier used at
 * call-time to select which set of OAuth scopes to request. Multiple
 * applications can be registered so that a single auth instance can serve
 * tokens for several downstream APIs.
 *
 * @example
 * ```ts
 * clientCredential({
 *   "graph-api": {
 *     scope: ["https://graph.microsoft.com/.default"],
 *   },
 *   "storage-api": {
 *     scope: ["https://storage.azure.com/.default"],
 *   },
 * })
 * ```
 */
export type ClientCredentialOptions = {
  [applicationName: string]: {
    /**
     * The OAuth 2.0 scopes to request from Microsoft for this application.
     * For client credentials flows, this is typically the `.default` scope of
     * a downstream API app registration, e.g.
     * `["api://<client-id>/.default"]`.
     */
    scope: string[];
  };
};

/**
 * A cached client-credential token record as stored in the database.
 *
 * The plugin writes one row per `applicationName`. Subsequent calls for the
 * same application return the cached record until it falls within the 60-second
 * pre-expiry refresh buffer, at which point the row is updated in place.
 */
export type ClientCredential = {
  /** Row primary key, generated by the Better Auth adapter. */
  id: string;
  /** ISO timestamp of when this record was first created. */
  createdAt: Date;
  /** ISO timestamp of the most recent token refresh. */
  updatedAt: Date;
  /**
   * The caller-supplied application name that identifies this credential set.
   * Matches a key in {@link ClientCredentialOptions}.
   */
  applicationName: string;
  /** The raw OAuth 2.0 Bearer access token returned by Microsoft. */
  accessToken: string;
  /**
   * The UTC datetime at which `accessToken` expires, computed from the
   * `expires_in` value returned by the Microsoft token endpoint.
   */
  accessTokenExpiresAt: Date;
  /**
   * Space-separated OAuth 2.0 scopes that were requested when this token was
   * issued, matching the `scope` array from {@link ClientCredentialOptions}.
   */
  scope: string;
};

/**
 * Better Auth plugin that implements the
 * [OAuth 2.0 client credentials flow](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow)
 * against **Microsoft Entra ID** (formerly Azure AD).
 *
 * The plugin fetches application-level access tokens on behalf of your server,
 * caches them in the Better Auth database, and refreshes them automatically
 * within a 60-second window before expiry. No user interaction is required.
 *
 * ---
 *
 * ### Prerequisites
 *
 * 1. The `microsoft` social provider must be configured in your `betterAuth`
 *    options with `tenantId`, `clientId`, and `clientSecret` for the Entra ID
 *    app registration that has the required **application permissions** (not
 *    delegated permissions) granted and admin-consented.
 *
 * 2. Run `npx @better-auth/cli migrate` (or `generate`) after adding this
 *    plugin so the `clientCredential` table is created in your database.
 *
 * ---
 *
 * ### Setup
 *
 * ```ts
 * // auth.ts
 * import { betterAuth } from "better-auth";
 * import { clientCredential } from "better-auth-client-credential";
 *
 * export const auth = betterAuth({
 *   database: yourDatabaseAdapter,
 *   socialProviders: {
 *     microsoft: {
 *       tenantId: process.env.ENTRA_TENANT_ID!,
 *       clientId: process.env.ENTRA_CLIENT_ID!,
 *       clientSecret: process.env.ENTRA_CLIENT_SECRET!,
 *     },
 *   },
 *   plugins: [
 *     clientCredential({
 *       "my-api": {
 *         scope: ["api://<downstream-app-client-id>/.default"],
 *       },
 *     }),
 *   ],
 * });
 * ```
 *
 * ### Usage
 *
 * `getClientCredentialToken` is a **server-only** endpoint (no HTTP route is
 * registered). Call it directly via `auth.api`:
 *
 * ```ts
 * const credential = await auth.api.getClientCredentialToken({
 *   body: { applicationName: "my-api" },
 * });
 *
 * // credential.accessToken — Bearer token to attach to downstream requests
 * // credential.accessTokenExpiresAt — expiry Date
 * // credential.scope — space-separated scopes that were granted
 * ```
 *
 * @param options - A map of application names to their OAuth scope configuration.
 *   Each key becomes a valid value for the `applicationName` field at call-time.
 *
 * @throws `MICROSOFT_APPLICATION_NOT_FOUND` (404) — the `applicationName`
 *   passed at call-time is not present in `options`.
 * @throws `MICROSOFT_PROVIDER_NOT_CONFIGURED` (500) — the `microsoft` social
 *   provider is absent from the Better Auth configuration.
 * @throws `MICROSOFT_PROVIDER_INVALID_CONFIG` (500) — the `microsoft` provider
 *   options are missing required fields (`tenantId`, `clientId`, `clientSecret`).
 * @throws `MICROSOFT_TOKEN_REQUEST_FAILED` (502) — the Microsoft token
 *   endpoint returned an error; the serialised error body is appended to the
 *   message for debugging.
 */
export const clientCredential = (options: ClientCredentialOptions) => {
  const PROVIDER_ID = "microsoft";

  const $fetch = createFetch({
    defaultError: defaultErrorSchema,
    schema: createSchema({
      "@post/token": {
        input: inputSchema,
        output: outputSchema,
      },
    }),
  });

  return {
    id: "client-credential",
    $ERROR_CODES: CLIENT_CREDENTIAL_ERRORS,
    schema: {
      clientCredential: {
        modelName: "clientCredential",
        fields: {
          createdAt: {
            type: "date",
            required: true,
            defaultValue: () => new Date(),
          },
          updatedAt: {
            type: "date",
            required: true,
            defaultValue: () => new Date(),
            onUpdate: () => new Date(),
          },
          applicationName: {
            type: "string",
            required: true,
            index: true,
          },
          accessToken: {
            type: "string",
            required: true,
          },
          accessTokenExpiresAt: {
            type: "date",
            required: true,
          },
          scope: {
            type: "string",
            required: true,
          },
        },
      },
    },
    endpoints: {
      getClientCredentialToken: createAuthEndpoint(
        {
          method: "POST",
          body: clientCredentialBodySchema,
        },
        async ({
          body: { applicationName },
          context: { adapter, socialProviders },
        }) => {
          const scope = options[applicationName]?.scope.join(" ");
          if (!scope) {
            throw APIError.from(
              "NOT_FOUND",
              CLIENT_CREDENTIAL_ERRORS.MICROSOFT_APPLICATION_NOT_FOUND,
            );
          }

          const cachedClientCredential =
            await adapter.findOne<ClientCredential>({
              model: "clientCredential",
              where: [
                {
                  field: "applicationName",
                  value: applicationName,
                  operator: "eq",
                },
              ],
            });

          const refreshThreshold = Date.now() + 60_000;
          if (
            cachedClientCredential &&
            cachedClientCredential.accessTokenExpiresAt &&
            cachedClientCredential.accessTokenExpiresAt.getTime() >
              refreshThreshold
          ) {
            return cachedClientCredential;
          }

          const oAuthProvider = socialProviders.find(
            ({ id }) => id === PROVIDER_ID,
          );

          if (!oAuthProvider?.options) {
            throw APIError.from(
              "INTERNAL_SERVER_ERROR",
              CLIENT_CREDENTIAL_ERRORS.MICROSOFT_PROVIDER_NOT_CONFIGURED,
            );
          }

          const { error: msConfigError, data: msOptions } =
            msSocialProviderConfigSchema.safeParse(oAuthProvider.options);
          if (msConfigError) {
            throw APIError.from("INTERNAL_SERVER_ERROR", {
              code: CLIENT_CREDENTIAL_ERRORS.MICROSOFT_PROVIDER_INVALID_CONFIG
                .code,
              message: `${
                CLIENT_CREDENTIAL_ERRORS.MICROSOFT_PROVIDER_INVALID_CONFIG
                  .message
              } ${msConfigError.message}`,
            });
          }

          const tenantId = msOptions.tenantId;

          // The Microsoft token endpoint requires application/x-www-form-urlencoded.
          const { error, data } = await $fetch("@post/token", {
            baseURL: `https://login.microsoftonline.com/${tenantId}/oauth2/v2.0`,
            headers: { "Content-Type": "application/x-www-form-urlencoded" },
            body: {
              tenant: tenantId,
              client_id: msOptions.clientId,
              client_secret: msOptions.clientSecret,
              scope: scope,
              grant_type: "client_credentials",
            },
          });

          if (error) {
            throw APIError.from("BAD_GATEWAY", {
              code: CLIENT_CREDENTIAL_ERRORS.MICROSOFT_TOKEN_REQUEST_FAILED
                .code,
              message: `${CLIENT_CREDENTIAL_ERRORS.MICROSOFT_TOKEN_REQUEST_FAILED.message}\n${JSON.stringify(error)}`,
            });
          }

          const now = new Date();
          const accessTokenExpiresAt = new Date(
            Date.now() + data.expires_in * 1000,
          );

          if (cachedClientCredential) {
            const updated = await adapter.update<ClientCredential>({
              model: "clientCredential",
              where: [
                {
                  field: "id",
                  value: cachedClientCredential.id,
                  operator: "eq",
                },
              ],
              update: {
                accessToken: data.access_token,
                accessTokenExpiresAt,
                updatedAt: now,
              },
            });
            return (
              updated ?? {
                ...cachedClientCredential,
                accessToken: data.access_token,
                accessTokenExpiresAt,
                updatedAt: now,
              }
            );
          }

          const created = await adapter.create<ClientCredential>({
            model: "clientCredential",
            data: {
              createdAt: now,
              updatedAt: now,
              applicationName,
              accessToken: data.access_token,
              accessTokenExpiresAt,
              scope,
            },
          });

          return created;
        },
      ),
    },
  } satisfies BetterAuthPlugin;
};
